/*
 * Copyright 2020 Piratkin Sergey
 *
 * Do not edit this file. It is automatically generated
 * by CMake and your changes will be overwritten.
 */

#ifndef PROJECT_H
#define PROJECT_H

#include <string>

typedef enum
{
    PROJECT_VERSION,
    PROJECT_PRODUCE,
    PROJECT_BUILD,
    // PROJECT_DATE,
    // PROJECT_TIME,
    PROJECT_QTY
} project_id_t;

inline const std::string &project_option(const project_id_t id) const
{
    switch (id)
    {
    case PROJECT_VERSION:
        return "0.7.0";
    case PROJECT_PRODUCE:
        return "51";
    case PROJECT_BUILD:
        return "142";
    // case PROJECT_DATE:
    //     return __BUILD_DATE;
    // case PROJECT_TIME:
    //     return __BUILD_TIME;
    }

    return "UNKNOWN";
}

#endif // PROJECT_H
