include(GNUInstallDirs)

# if(NOT CMAKE_INSTALL_LIBDIR)
#   set(CMAKE_INSTALL_LIBDIR "lib")
# endif()

# if(NOT CMAKE_INSTALL_BINDIR)
#   set(CMAKE_INSTALL_BINDIR "bin")
# endif()

# if(NOT CMAKE_INSTALL_INCLUDEDIR)
#   set(CMAKE_INSTALL_INCLUDEDIR "include")
# endif()

# if(NOT CMAKE_INSTALL_DOCDIR)
#   set(CMAKE_INSTALL_DOCDIR "share/${PROJECT_NAME}/docs")
# endif()

message (STATUS "CMAKE_INSTALL_LIBDIR: ${CMAKE_INSTALL_LIBDIR}")
message (STATUS "CMAKE_INSTALL_BINDIR: ${CMAKE_INSTALL_BINDIR}")
message (STATUS "CMAKE_INSTALL_INCLUDEDIR: ${CMAKE_INSTALL_INCLUDEDIR}")
message (STATUS "CMAKE_INSTALL_DOCDIR: ${CMAKE_INSTALL_DOCDIR}")
